version: "3"

services:

   portainer-ce:
      container_name: portainer-ce
      image: portainer/portainer-ce

      restart: always
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: 10m

      ports:
         - "9001:9000"

      volumes:
         - /var/run/docker.sock:/var/run/docker.sock         
         - portainer_data_dir:/data


volumes:
   portainer_data_dir:
      external: true
